let num1= 31;
let num2 = 2;            
let multiply = (num1 * num2)
let random = (Math.floor(Math.random() * 10) + 1);
let num3 = 34;
let num4 = 6;            
let mod = (num3 % num4)
let x = 5;
let y = 6;
let z = 20;              
let max = (Math.max(x,y,z))
